//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorLocalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorLocalization.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Classification.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomacy.
        /// </summary>
        public static string Diplomacy {
            get {
                return ResourceManager.GetString("Diplomacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Approval.
        /// </summary>
        public static string EngineeringApproval {
            get {
                return ResourceManager.GetString("EngineeringApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration.
        /// </summary>
        public static string Exploration {
            get {
                return ResourceManager.GetString("Exploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} too long ({1} character limit)..
        /// </summary>
        public static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Accommodation.
        /// </summary>
        public static string MaximumAccommodation {
            get {
                return ResourceManager.GetString("MaximumAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ship Entry Form.
        /// </summary>
        public static string New_Ship_Entry_Form {
            get {
                return ResourceManager.GetString("New Ship Entry Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        public static string optional {
            get {
                return ResourceManager.GetString("optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Date.
        /// </summary>
        public static string ProductionDate {
            get {
                return ResourceManager.GetString("ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} has invalid range ({1}-{2}).
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select classification ....
        /// </summary>
        public static string Select_classification____ {
            get {
                return ResourceManager.GetString("Select classification ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starfleet Starship Database.
        /// </summary>
        public static string Starfleet_Starship_Database {
            get {
                return ResourceManager.GetString("Starfleet Starship Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form disallows unapproved ships..
        /// </summary>
        public static string ValidatedDesignError {
            get {
                return ResourceManager.GetString("ValidatedDesignError", resourceCulture);
            }
        }
    }
}
